- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleArmsDealer
  name: Arms Dealer Role
  components:
    - type: MindRole
      antagPrototype: ArmsDealer
      roleType: SoloAntagonist
    - type: ArmsDealerRole
